@startuml
interface AppleTree {
    +growFruit(): void
}
class AppleTreeImpl implements AppleTree {
    -random: Random
    +growFruit(): void
}
class BirchTreeImpl {
    +releaseSap(): void
}
class BirchTreeToAppleTreeAdapter implements AppleTree {
    -birchTree: BirchTreeImpl
    +BirchTreeAdapter(newBirchTree: BirchTreeImpl)
    +growFruit(): void
}
@enduml